# Generated by Django 4.2.9 on 2024-08-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-pk',), 'permissions': {('block_user', 'Может блокировать пользователя')}, 'verbose_name': 'пользователя', 'verbose_name_plural': 'пользователи'},
        ),
    ]
