# Generated by Django 5.0.7 on 2024-07-29 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите Ф.И.О.', max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Введите email', max_length=150, unique=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиента',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тему сообщения', max_length=150, verbose_name='Тема')),
                ('body', models.TextField(help_text='Введите сообщение', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Рассылка', help_text='Введите наименование рассылки', max_length=150, null=True, verbose_name='Наименование')),
                ('trigger', models.DateTimeField(help_text='Введите время и дату первого запуска', verbose_name='Время и дата')),
                ('periodicity', models.CharField(choices=[('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')], default='D', help_text='Выберите периодичность запуска', max_length=1, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('C', 'Создана'), ('R', 'Запущена'), ('F', 'Завершена')], default='C', help_text='Выберите статус рассылки', max_length=1, verbose_name='Статус')),
                ('clinents', models.ManyToManyField(help_text='Выберите клиентов', to='sender.client', verbose_name='Клиенты')),
                ('text', models.ForeignKey(auto_created=True, help_text='Выберите сообщение для рассылки', on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='sender.text')),
            ],
            options={
                'verbose_name': 'рассылку',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
