# Generated by Django 5.0.7 on 2024-08-04 06:48

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ф.И.О')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиента',
                'verbose_name_plural': 'клиенты',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тема')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите наименование рассылки', max_length=150, null=True, verbose_name='Наименование')),
                ('start_datetime', models.DateTimeField(help_text='Введите время и дату старта', verbose_name='Время и дата старта')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Введите время и дату окончания (не обязательно)', null=True, verbose_name='Время и дата окончания')),
                ('periodicity', models.CharField(choices=[('O', 'Одноразовая'), ('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')], default='O', help_text='Выберите периодичность запуска', max_length=1, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('C', 'Создана'), ('R', 'Запущена'), ('S', 'Завершена')], default='C', help_text='Выберите статус рассылки', max_length=1, verbose_name='Статус')),
                ('clients', models.ManyToManyField(help_text='Выберите клиентов', to='sender.client', verbose_name='Клиенты')),
                ('text', models.ForeignKey(help_text='Выберите сообщение для рассылки', on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='sender.text', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'рассылку',
                'verbose_name_plural': 'рассылки',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now=True, verbose_name='Дата и время запуска')),
                ('status', models.BooleanField(default=True, editable=False, verbose_name='Статус')),
                ('response_code', models.SmallIntegerField(editable=False, verbose_name='Код ответа')),
                ('response_msg', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Текст ответа сервера')),
                ('mailing', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='sender.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'попытку',
                'verbose_name_plural': 'попытки',
                'ordering': ('-started',),
            },
        ),
    ]
