# Generated by Django 5.0.7 on 2024-07-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('pk',), 'verbose_name': 'клиента', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('pk',), 'verbose_name': 'рассылку', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ('pk',), 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='trigger',
            new_name='started_at',
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(blank=True, help_text='Введите наименование рассылки', max_length=150, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='text',
            field=models.ForeignKey(help_text='Выберите сообщение для рассылки', on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='sender.text', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='text',
            name='body',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Тема'),
        ),
    ]
