# Generated by Django 4.2.9 on 2024-08-21 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0002_client_owner_mailing_owner_text_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('pk',), 'permissions': {('disable_mailing', 'Может отключать рассылку')}, 'verbose_name': 'рассылку', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='sender.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время и дата окончания'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('O', 'Одноразовая'), ('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')], default='O', max_length=1, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Время и дата старта'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('C', 'Создана'), ('R', 'Запущена'), ('S', 'Завершена')], default='C', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='sender.text', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='text',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
