# Generated by Django 5.0.7 on 2024-07-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_alter_mailing_periodicity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='clinents',
            new_name='clients',
        ),
    ]
