# Generated by Django 5.0.7 on 2024-07-31 09:55

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_rename_clinents_mailing_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('C', 'Создана'), ('R', 'Запущена'), ('S', 'Завершена')], default='C', help_text='Выберите статус рассылки', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='text',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now=True, verbose_name='Дата и время запуска')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('response', models.CharField(max_length=250, verbose_name='Ответ сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sender.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'попытку',
                'verbose_name_plural': 'попытки',
                'ordering': ('pk',),
            },
        ),
    ]
