# Generated by Django 5.0.7 on 2024-07-31 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_alter_mailing_status_alter_text_body_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='mailing',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='sender.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='response',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Ответ сервера'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Статус'),
        ),
    ]
