# Generated by Django 5.0.7 on 2024-07-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_alter_attempt_mailing_alter_attempt_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='response',
        ),
        migrations.AddField(
            model_name='attempt',
            name='response_code',
            field=models.SmallIntegerField(default=0, editable=False, verbose_name='Код ответа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='response_msg',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Текст ответа сервера'),
        ),
    ]
