# Generated by Django 5.0.7 on 2024-08-01 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_remove_attempt_response_attempt_response_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='started_at',
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Введите время и дату окончания', verbose_name='Время и дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Введите время и дату старта', verbose_name='Время и дата старта'),
            preserve_default=False,
        ),
    ]
