# Generated by Django 5.0.7 on 2024-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_remove_mailing_started_at_mailing_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ('-started',), 'verbose_name': 'попытку', 'verbose_name_plural': 'попытки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Введите время и дату окончания (не обязательно)', null=True, verbose_name='Время и дата окончания'),
        ),
    ]
