# Generated by Django 4.2.9 on 2024-08-22 09:29

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Содержимое статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('views_count', models.IntegerField(default=0, editable=False, verbose_name='Количество просмотров')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('public_date', models.DateField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'статью',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-id',),
            },
        ),
    ]
